services:
  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: resume_builder
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - resume-network
    restart: unless-stopped

  postgres_test:
    container_name: postgres_test
    image: postgres
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: resume_builder_test
    volumes:
      - postgres_test:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - resume-network
    restart: unless-stopped
  
  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:26.0.5
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin 
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
    volumes:
      - ./realm-config:/opt/keycloak/data/import
    command: 
      - "start-dev"
      - "--import-realm"
    ports:
      - "9090:8080"
    networks:
      - resume-network

  backend:
    build: ./backend
    container_name: resume-backend
    volumes:
      - ./uploads:/app/uploads 
      - ./backend:/app  
      - ~/.m2:/root/.m2  
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_DEVTOOLS_RESTART_ENABLED: true
    ports:
      - "8080:8080"
      - "5005:5005" 
    network_mode: "host"
    depends_on:
      - postgres
      - keycloak
      
  frontend:
    build: ./frontend
    container_name: resume-frontend
    ports:
      - "4200:4200"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    networks:
      - resume-network
    depends_on:
      - backend
      - keycloak

networks:
  resume-network:
    driver: bridge

volumes:
  postgres:
  postgres_test:
    driver: local
  keycloak:
    driver: local