services:
  postgres:
    container_name: postgres-sql-bsn
    image: postgres
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: resume_builder
    volumes:
      - postgres:/data/postgres
    ports:
      - 5432:5432
    networks:
      - default
    restart: unless-stopped 
  
  mail-dev:
    container_name: mail-dev-bsn
    image: maildev/maildev
    ports:
      - 1080:1080
      - 1025:1025
  
  keycloak:
    container_name: keycloak-bsn
    image: quay.io/keycloak/keycloak:24.0.2
    ports:
      - 9090:8080
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    networks:
      - default
    command:
      - "start-dev"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "4200:4200"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - API_URL=http://localhost:8080

  backend:
    build:
      context: ./resume.builder
      dockerfile: Dockerfile.dev
    ports:
      - "8080:8080"
    volumes:
      - ./resume.builder:/app
      - ~/.m2:/root/.m2

networks:
  default:
    driver: bridge

volumes:
  postgres:
      driver: local
  keycloak:
    driver: local