services:
  postgres:
    container_name: postgres-sql-bsn
    image: postgres
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: resume_builder
    volumes:
      - postgres:/data/postgres
    ports:
      - 5432:5432
    networks:
      - default
    restart: unless-stopped 
  
  keycloak:
    container_name: keycloak-bsn
    image: quay.io/keycloak/keycloak:26.0.5
    ports:
      - 9090:8080
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    networks:
      - default
    command:
      - "start-dev"
      
networks:
  default:
    driver: bridge

volumes:
  postgres:
      driver: local
  keycloak:
    driver: local