spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/resume_builder
    username: username
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    database: postgresql
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: "http://localhost:9090/realms/resume-builder"

application:
  file:
    uploads:
      photos-output-path: ./uploads
      
server:
  port: 8088
